[package]
name = "jetstream_rpc"
version = "5.0.0"
edition = "2021"
description = "Jetstream is a RPC framework for Rust, based on the 9P protocol and QUIC."
license = "BSD-3-Clause"
repository = "https://github.com/sevki/jetstream"


[dependencies]
async-trait = "0.1.83"
git2 = { version = "0.18.3", optional = true }
jetstream_wireformat = { version = "5.0.0", path = "../jetstream_wireformat" }
okstd = { version = "0.1.10" }
tokio = { version = "1.40.0", features = ["full"] }

[features]
git2 = ["dep:git2"]
