[package]
name = "jetstream_9p"
version = "5.0.0"
edition = "2021"
description = "Jetstream is a RPC framework for Rust, based on the 9P protocol and QUIC."
license = "BSD-3-Clause"
repository = "https://github.com/sevki/jetstream"

[dependencies]
jetstream_derive = { version = "5.0.0", path = "../jetstream_derive" }
jetstream_wireformat = { version = "5.0.0", path = "../jetstream_wireformat" }
jetstream_rpc = { version = "5.0.0", path = "../jetstream_rpc" }
libc = "0.2.159"
async-trait = "0.1.83"
