name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # This will match tags like v5.4.1, v1.0.0, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
